# Generated by Django 3.1.3 on 2021-09-30 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('direccion', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=10)),
                ('nacionalidad', models.CharField(max_length=20)),
                ('correo', models.EmailField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('num_orden', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('fecha_orden', models.DateField()),
                ('estado', models.CharField(max_length=10)),
                ('id_cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_cliente.cliente')),
            ],
        ),
    ]
