# Generated by Django 3.1.3 on 2021-09-30 21:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_cliente', '0003_auto_20210930_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='fecha_orden',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 30, 16, 8, 44, 409875)),
        ),
    ]
