# Generated by Django 3.1.3 on 2021-09-30 22:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_cliente', '0004_auto_20210930_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='detalle',
            field=models.TextField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='orden',
            name='fecha_orden',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 30, 17, 22, 7, 46908)),
        ),
    ]
