# Generated by Django 3.1.3 on 2021-10-01 07:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_cliente', '0005_auto_20210930_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='fecha_orden',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 1, 2, 36, 32, 819511)),
        ),
    ]
